<!DOCTYPE html>
<html>
  <head>
    <title>Jordi López | Full-stack Developer</title>
    <meta name="description" content="Jordi López, Full-stack developer based in Barcelona, Spain. Building things with code. Passionate about Javascript, Nodejs and WebPerformance.">
    <meta name="author" content="Jordi López">
    <meta charset="utf-8">
    <link rel="canonical" href="http://jlopezxs.github.io/">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/style.css" type="text/css" rel="stylesheet">
  </head>

  <body>
    <section class="header">
      <div class="container">
        <div class="row">
          <div class="col col--6">
            <h1 class="header__title">Hi, I'm <span class="title__accent">Jordi López</span></h1>
            <h2 class="header__sub-title">I'm Full-stack developer based in Barcelona, Spain. You can follow me on 
          <a href="https://twitter.com/jlopezxs">twitter</a> and <a href="https://github.com/jlopezxs">github</a>. Full resume <a href="https://es.linkedin.com/in/jordi-l%C3%B3pez-ram%C3%ADrez-5830749a">here</a></h2> <a target="_blank" href="#" class="btn btn--primary">Contact Me</a> </div>
          <div class="col col--6"> </div>
        </div>
      </div>
    </section>
  </body>
</html>